# Generated by Django 2.1b1 on 2018-07-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGener', '0004_auto_20180717_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compose',
            name='ingre',
        ),
        migrations.RemoveField(
            model_name='compose',
            name='name',
        ),
        migrations.AlterField(
            model_name='canget',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Compose',
        ),
    ]
