# Generated by Django 2.1b1 on 2018-07-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGener', '0005_auto_20180717_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AutoGener.CanDo')),
                ('ingre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AutoGener.CanGet')),
            ],
        ),
    ]
