# Generated by Django 2.1b1 on 2018-07-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGener', '0008_auto_20180718_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cando',
            name='ingre',
            field=models.ManyToManyField(blank=True, to='AutoGener.CanGet'),
        ),
    ]
