# Generated by Django 2.1b1 on 2018-07-23 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGener', '0009_auto_20180718_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cando',
            name='type',
        ),
        migrations.AddField(
            model_name='compose',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AutoGener.CanDo'),
        ),
        migrations.AddField(
            model_name='compose',
            name='ingre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AutoGener.CanGet'),
        ),
        migrations.AddField(
            model_name='cando',
            name='type',
            field=models.ManyToManyField(to='AutoGener.DishType'),
        ),
    ]
