# Generated by Django 2.0.7 on 2018-08-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGener', '0010_auto_20180723_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='cando',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canget',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishtype',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
