# Generated by Django 2.0.7 on 2018-08-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGener', '0011_auto_20180803_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canget',
            name='cal',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
