# Generated by Django 2.0.7 on 2018-08-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoGener', '0012_auto_20180804_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canget',
            name='cal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
